version: '3'
services:
  db:
    image: postgres:10.1-alpine
    environment:
      POSTGRES_USER: shuyang
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: twitter
    ports:
      - "5432:5432"
    volumes:
      - ./dbinit/twitter.sql:/docker-entrypoint-initdb.d/a.sql


  apiservice:
    build: ./apiserver
    volumes:
      - ./apiserver:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  dbinit:


